### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by jfoggo** [jfoggo/PDF-Merger#3]
- [ ] Mobile Responive
- [ ] Service Worker für Offline Funktionalität
- [ ] Toggle (pdf/snippet) in select sidebar
- [x] Filenames unter PDF (Preload img)
- [ ] Future: Unterteilung der PDF's in Projekte/Unterordner+
- [ ] Dateien, die nicht gerendert werden können, sollen abgefangen werden!
- [ ] WebApp in gängigen Browsern testen (manifest.json)
